const $=s=>document.querySelector(s);let mode='login',user=JSON.parse(localStorage.getItem('adk_user')||'null'),ads=[];
const save=()=>localStorage.setItem('adk_user',JSON.stringify(user));const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(p,o){const r=await fetch(p,o);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function setMode(m){mode=m;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#regFields').hidden=m!=='register';$('#loginId').placeholder=m==='register'?'Email':'ID or Email';$('#authSubmit').textContent=m==='register'?'Create Account':'Login';$('#authMsg').textContent=''}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='Processing…';try{if(mode==='register'){const d=await api('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#name').value,email:$('#loginId').value,password:$('#password').value,role:$('#role').value,parentId:$('#parentId').value})});$('#authMsg').textContent=`Registration successful. Your ${d.user.role} ID is ${d.user.id}.`;setMode('login');$('#loginId').value=d.user.email}else{const d=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:$('#loginId').value,password:$('#password').value,role:'user'})});user=d.user;save();render()}}catch(x){$('#authMsg').textContent=x.message}};
$('#logoutBtn').onclick=()=>{user=null;localStorage.removeItem('adk_user');render()};
async function render(){if(!user){$('#authView').hidden=false;$('#appView').hidden=true;$('#logoutBtn').hidden=true;return}$('#authView').hidden=true;$('#appView').hidden=false;$('#logoutBtn').hidden=false;$('#userName').textContent=user.name;$('#userMeta').textContent=`ID: ${user.id} • Parent ID: ${user.parentId||'ADMIN-001'} • Role: ${user.role.toUpperCase()}`;$('#roleLabel').textContent=user.role==='client'?'CLIENT DASHBOARD':'VIEWER DASHBOARD';$('#balance').textContent=Number(user.balance||0).toFixed(2);$('#balanceLabel').textContent=user.role==='client'?'Campaign Account':'Total Earning';$('#balanceSub').textContent=user.role==='client'?'Advertising account':'Available demo balance';await loadAds();buildStats();buildNav();openPage(user.role==='client'?'campaigns':'ads')}
async function loadAds(){try{ads=(await api('/api/ads')).ads||[]}catch{ads=[]}}
function buildStats(){if(user.role==='client'){$('#stats').innerHTML=`<div class="card stat"><span>Client ID</span><b>${esc(user.id)}</b></div><div class="card stat"><span>Approved Ads</span><b>${ads.filter(a=>a.clientId===user.id).length}</b></div><div class="card stat"><span>Parent ID</span><b>${esc(user.parentId||'ADMIN-001')}</b></div>`}else{$('#stats').innerHTML=`<div class="card stat"><span>Total Earning</span><b>₹${Number(user.balance||0).toFixed(2)}</b></div><div class="card stat"><span>Ads Watched</span><b>${user.adsWatched||0}</b></div><div class="card stat"><span>Withdraw</span><b>${user.payout?'Ready':'Set payout account'}</b></div>`}}
function buildNav(){
 const items=user.role==='client'
 ?[['campaigns','fa-bullhorn','My Ads','Submit campaign'],['history','fa-clock-rotate-left','Ad History','Campaign status'],['profile','fa-id-card','My ID','Account & parent ID'],['help','fa-circle-question','Help','Support & FAQs']]
 :[['ads','fa-circle-play','Watch Ads','Approved ads only'],['packages','fa-layer-group','Packages','Viewer access plans'],['earnings','fa-coins','Total Earning','Earnings overview'],['payout','fa-wallet','Payout Account','Set before withdrawal'],['withdraw','fa-money-bill-transfer','Withdraw','Request payout'],['history','fa-clock-rotate-left','History','Ads & withdrawals'],['profile','fa-id-card','My ID','Account details'],['help','fa-circle-question','Help','Support & FAQs']];
 $('#nav').innerHTML=items.map(x=>`<button class="navcard" data-page="${x[0]}"><span><i class="fa-solid ${x[1]}"></i></span><b>${x[2]}</b><small>${x[3]}</small></button>`).join('');
 const mobile=items.slice(0,4);
 $('#mobileNav').innerHTML=mobile.map(x=>`<button data-page="${x[0]}"><i class="fa-solid ${x[1]}"></i><span>${x[2]}</span></button>`).join('')+
 `<button id="moreBtn"><i class="fa-solid fa-ellipsis"></i><span>More</span></button>`;
 const moreItems=items.slice(4);
 $('#moreSheet').innerHTML=moreItems.map(x=>`<button data-page="${x[0]}"><i class="fa-solid ${x[1]}"></i> ${x[2]}</button>`).join('');
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>openPage(b.dataset.page));
 const mb=$('#moreBtn'); if(mb) mb.onclick=()=>$('#moreSheet').classList.toggle('open');
}
function openPage(p){
 $('#moreSheet')?.classList.remove('open');
 document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));
 if(p==='ads')adsPage();if(p==='packages')packagesPage();if(p==='earnings')earningsPage();if(p==='payout')payoutPage();if(p==='withdraw')withdrawPage();if(p==='history')historyPage();if(p==='profile')profilePage();if(p==='campaigns')campaignPage();if(p==='help')helpPage();
}
function adsPage(){$('#pageArea').innerHTML=`<div class="section card"><div class="section-head"><div><h2>Approved Live Ads</h2><p class="muted">Only ads approved by admin appear here.</p></div><span class="live-dot">● SERVER ADS</span></div><div class="adgrid">${ads.length?ads.map(a=>`<div class="ad"><span class="tag">APPROVED AD</span><h3>${esc(a.title)}</h3><p class="muted">${esc(a.description)}</p><b class="reward">+₹${Number(a.reward||0).toFixed(2)}</b>${a.url?`<a class="adlink" href="${esc(a.url)}" target="_blank">Advertiser ↗</a>`:''}<button class="primary" onclick="watch('${a.id}')">Watch & Earn</button></div>`).join(''):'<p class="muted">No approved ads are available yet.</p>'}</div></div>`}
function packagesPage(){
 const current=localStorage.getItem('adk_package')||'Free Viewer';
 const packs=[
  ['Starter','₹500','2','Entry package display'],
  ['Standard','₹1000','5','Standard package display'],
  ['Premium','₹2000','12','Premium package display']
 ];
 $('#pageArea').innerHTML=`<div class="section card package-section"><div class="section-head"><div><h2>Viewer Packages</h2><p class="muted">Package selection is shown for demonstration. Payment and fixed-return promises are not enabled in this build.</p></div><span class="live-dot">PACKAGE LIST</span></div><div class="packgrid">
 ${packs.map(x=>`<div class="package-card ${current===x[0]?'featured':''}"><span class="package-icon"><i class="fa-solid fa-box-open"></i></span><h3>${x[0]}</h3><p>${x[3]} • Includes ${x[2]} package units.</p><b>${x[1]}</b><small class="muted">Units: ${x[2]}</small><button class="primary" onclick="selectPackage('${x[0]}')">${current===x[0]?'Selected':'Select'}</button></div>`).join('')}</div>
 <div class="warning" style="margin-top:16px">Before accepting real payments or advertising guaranteed returns, verify the applicable legal, financial and consumer-protection requirements for your business.</div>
 </div>`;
}
function selectPackage(name){localStorage.setItem('adk_package',name);packagesPage()}
function helpPage(){
 $('#pageArea').innerHTML=`<div class="section card"><div class="section-head"><div><h2>Help & Support</h2><p class="muted">Quick help for login, ads, packages and account issues.</p></div><span class="live-dot">SUPPORT</span></div><div class="help-grid">
 <div class="help-item"><i class="fa-solid fa-right-to-bracket"></i><h3>Login</h3><p>Use your registered ID or email and password. Incorrect details will show an error.</p></div>
 <div class="help-item"><i class="fa-solid fa-circle-play"></i><h3>Watch Ads</h3><p>Only approved advertisements are displayed in the Watch Ads section.</p></div>
 <div class="help-item"><i class="fa-solid fa-layer-group"></i><h3>Packages</h3><p>Select a package to highlight it on your dashboard. Payment is not enabled in this demo build.</p></div>
 <div class="help-item"><i class="fa-solid fa-wallet"></i><h3>Payout</h3><p>Save your payout account before requesting a withdrawal.</p></div>
 <div class="help-item"><i class="fa-solid fa-clock-rotate-left"></i><h3>History</h3><p>Review your watch and withdrawal records from the History section.</p></div>
 <div class="help-item"><i class="fa-solid fa-headset"></i><h3>Need support?</h3><p>Ask your administrator for account, payout or package-related assistance.</p></div>
 </div></div>`;
}
function earningsPage(){$('#pageArea').innerHTML=`<div class="section card"><h2>Total Earning</h2><div class="earning-big">₹${Number(user.balance||0).toFixed(2)}</div><div class="earning-grid"><div><span>Ads watched</span><b>${user.adsWatched||0}</b></div><div><span>Available balance</span><b>₹${Number(user.balance||0).toFixed(2)}</b></div><div><span>Payout account</span><b>${user.payout?'Ready':'Not set'}</b></div></div></div>`}
function payoutPage(){const p=user.payout||{};$('#pageArea').innerHTML=`<div class="section card"><h2>Payout Account</h2><p class="muted">Withdrawal will stay locked until this account is saved.</p><form onsubmit="savePayout(event)"><select id="ptype" required><option value="">Choose method</option><option ${p.type==='UPI'?'selected':''}>UPI</option><option ${p.type==='BANK'?'selected':''}>BANK</option></select><input id="pname" placeholder="Account holder name" value="${esc(p.name||'')}" required><input id="pupi" placeholder="UPI ID" value="${esc(p.upi||'')}"><input id="pacc" placeholder="Bank account number" value="${esc(p.account||'')}"><input id="pifsc" placeholder="IFSC" value="${esc(p.ifsc||'')}"><button class="primary">Save Payout Account</button></form></div>`}
async function savePayout(e){e.preventDefault();try{const type=$('#ptype').value;user.payout={type,name:$('#pname').value,upi:type==='UPI'?$('#pupi').value:'',account:type==='BANK'?$('#pacc').value:'',ifsc:type==='BANK'?$('#pifsc').value:''};await api('/api/payout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...user.payout,userId:user.id})});save();render()}catch(x){alert(x.message)}}
function withdrawPage(){$('#pageArea').innerHTML=`<div class="section card"><h2>Withdraw</h2><div class="withdraw-card"><div><span>Available</span><b>₹${Number(user.balance||0).toFixed(2)}</b></div><div><span>Minimum</span><b>₹100</b></div><div><span>Account</span><b>${user.payout?'Ready':'Locked'}</b></div></div>${!user.payout?'<p class="warning">First set your Payout Account.</p>':Number(user.balance||0)<100?'<p class="warning">Minimum withdrawal is ₹100.</p>':'<button class="primary" onclick="withdraw()">Request Withdrawal</button>'}</div>`}
async function withdraw(){try{await api('/api/withdraw',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:user.id})});user.balance=0;save();render();alert('Withdrawal request sent to admin.')}catch(x){alert(x.message)}}
function historyPage(){const h=user.watchHistory||[];$('#pageArea').innerHTML=`<div class="section card"><h2>My History</h2><table class="history"><tr><th>Ad</th><th>Reward</th><th>Date</th></tr>${h.slice().reverse().map(x=>`<tr><td>${esc(x.title)}</td><td>+₹${Number(x.reward).toFixed(2)}</td><td>${new Date(x.date).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="3">No history yet.</td></tr>'}</table></div>`}
function profilePage(){$('#pageArea').innerHTML=`<div class="section card"><h2>My Account</h2><div class="info-grid"><div><span>My ID</span><b>${esc(user.id)}</b></div><div><span>Role</span><b>${esc(user.role)}</b></div><div><span>Parent ID</span><b>${esc(user.parentId||'ADMIN-001')}</b></div><div><span>Approval</span><b>Approved</b></div></div></div>`}
function campaignPage(){$('#pageArea').innerHTML=`<div class="section card"><h2>Create Advertisement</h2><p class="muted">Your campaign will remain hidden from viewers until admin approves it.</p><form onsubmit="submitAd(event)"><input id="ctitle" placeholder="Product / campaign name" required><textarea id="cdesc" placeholder="Advertisement description" required></textarea><input id="curl" placeholder="Advertiser URL"><input id="creward" type="number" min="1" value="10" placeholder="Reward per completed ad"><button class="primary">Submit For Admin Approval</button></form></div><div class="section card"><h2>My Campaigns</h2>${ads.filter(a=>a.clientId===user.id).map(a=>`<div class="ad"><b>${esc(a.title)}</b><p class="muted">${esc(a.description)}</p><span class="tag">${esc(a.status)}</span></div>`).join('')||'<p class="muted">No approved campaigns visible yet.</p>'}</div>`}
async function submitAd(e){e.preventDefault();try{await api('/api/ads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:user.id,title:$('#ctitle').value,description:$('#cdesc').value,url:$('#curl').value,reward:Number($('#creward').value)})});alert('Ad submitted. Admin approval is required.');await loadAds();openPage('campaigns')}catch(x){alert(x.message)}}
function watch(id){const a=ads.find(x=>x.id===id);let s=10;modal(`<div class="center"><span class="tag">ADVERTISEMENT</span><h2>${esc(a.title)}</h2><p class="muted">Demo watch timer. Complete it to record the earning.</p><div class="timer" id="timer">10</div><div class="progress"><div id="bar"></div></div><button class="primary" id="claim" disabled>Watching…</button></div>`);const t=setInterval(()=>{s--;$('#timer').textContent=s;$('#bar').style.width=((10-s)/10*100)+'%';if(s<=0){clearInterval(t);$('#claim').disabled=false;$('#claim').textContent=`Claim ₹${Number(a.reward).toFixed(2)}`;$('#claim').onclick=async()=>{try{const d=await api('/api/watch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:user.id,adId:id})});user.balance=d.balance;user.adsWatched=(user.adsWatched||0)+1;save();closeModal();render()}catch(x){alert(x.message)}}}},1000)}
function modal(h){$('#modalContent').innerHTML=h;$('#modal').hidden=false}function closeModal(){$('#modal').hidden=true}render();
