const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||10000,ROOT=__dirname,DB=path.join(ROOT,'data.json');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8'};
function db(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return {admin:{id:'ADMIN-001',name:'Add Dekho K Admin',email:'admin@adddekhok.local',password:'Admin@123',role:'admin'},users:[],ads:[],payments:[],withdrawals:[]}}}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function json(res,s,d){res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(d))}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on('error',no)})}
function id(prefix){return `${prefix}-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`}
function safeUser(u){const {password,...x}=u;return x}
function findUser(d,uid){return d.users.find(u=>u.id===uid)}
const server=http.createServer(async(req,res)=>{
 const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
 try{
  if(p==='/api/register'&&req.method==='POST'){const b=await body(req),d=db(),role=b.role==='client'?'client':'viewer';if(!b.name||!b.email||!b.password)return json(res,400,{error:'Name, email and password are required'});if(d.users.some(x=>x.email.toLowerCase()===String(b.email).toLowerCase()))return json(res,409,{error:'Email already registered'});if(b.parentId&&!d.users.some(x=>x.id===b.parentId)&&b.parentId!==d.admin.id)return json(res,400,{error:'Parent ID not found'});const prefix=role==='client'?'CL':'VW';const x={id:id(prefix),name:String(b.name).trim().slice(0,100),email:String(b.email).trim().toLowerCase(),password:String(b.password),role,parentId:String(b.parentId||d.admin.id),approved:false,createdAt:new Date().toISOString(),balance:0,adsWatched:0};d.users.push(x);save(d);return json(res,201,{user:safeUser(x),message:'Registration submitted. Admin approval is required.'})}
  if(p==='/api/login'&&req.method==='POST'){const b=await body(req),d=db();if(b.role==='admin'){if(b.id===d.admin.id&&b.password===d.admin.password)return json(res,200,{user:safeUser(d.admin),admin:true});return json(res,401,{error:'Invalid admin login'})}const x=d.users.find(v=>v.id===b.id||v.email===String(b.id||'').toLowerCase());if(!x||x.password!==b.password)return json(res,401,{error:'Invalid ID/email or password'});if(!x.approved)return json(res,403,{error:'Account is waiting for admin approval'});return json(res,200,{user:safeUser(x),admin:false})}
  if(p==='/api/ads'&&req.method==='GET'){const d=db(),approved=d.ads.filter(a=>a.status==='approved');return json(res,200,{ads:approved})}
  if(p==='/api/ads'&&req.method==='POST'){const b=await body(req),d=db();if(!b.title||!b.description)return json(res,400,{error:'Title and description required'});const ad={id:id('AD'),clientId:b.clientId||d.admin.id,title:String(b.title).slice(0,120),description:String(b.description).slice(0,1000),url:String(b.url||'').slice(0,500),reward:Number(b.reward)||10,status:b.clientId?'pending':'approved',createdAt:new Date().toISOString(),approvedAt:b.clientId?null:new Date().toISOString()};d.ads.push(ad);save(d);return json(res,201,{ad})}
  if(p==='/api/watch'&&req.method==='POST'){const b=await body(req),d=db(),x=findUser(d,b.userId),ad=d.ads.find(a=>a.id===b.adId&&a.status==='approved');if(!x||x.role!=='viewer'||!x.approved)return json(res,403,{error:'Approved viewer account required'});if(!ad)return json(res,404,{error:'Ad unavailable'});const reward=Math.max(0,Number(ad.reward)||0);x.balance=(Number(x.balance)||0)+reward;x.adsWatched=(x.adsWatched||0)+1;x.watchHistory=x.watchHistory||[];x.watchHistory.push({adId:ad.id,title:ad.title,reward,date:new Date().toISOString()});save(d);return json(res,200,{reward,balance:x.balance})}
  if(p==='/api/withdraw'&&req.method==='POST'){const b=await body(req),d=db(),x=findUser(d,b.userId);if(!x||x.role!=='viewer')return json(res,403,{error:'Viewer account required'});if(!x.payout)return json(res,400,{error:'Set payout account first'});const amount=Number(x.balance)||0;if(amount<100)return json(res,400,{error:'Minimum withdrawal is ₹100'});const w={id:id('WD'),userId:x.id,amount,method:x.payout.type,status:'pending',createdAt:new Date().toISOString()};x.balance=0;d.withdrawals.push(w);save(d);return json(res,201,{withdrawal:w})}
  if(p==='/api/payout'&&req.method==='POST'){const b=await body(req),d=db(),x=findUser(d,b.userId);if(!x||x.role!=='viewer')return json(res,403,{error:'Viewer account required'});if(!b.type||!b.name)return json(res,400,{error:'Payout details required'});x.payout={type:b.type,name:String(b.name).slice(0,100),upi:b.type==='UPI'?String(b.upi||'').slice(0,100):'',account:b.type==='BANK'?String(b.account||'').slice(0,30):'',ifsc:b.type==='BANK'?String(b.ifsc||'').slice(0,20):''};save(d);return json(res,200,{payout:x.payout})}
  if(p==='/api/admin'&&req.method==='GET'){const d=db();if(u.searchParams.get('key')!=='Admin@123')return json(res,401,{error:'Admin authentication required'});const users=d.users.map(safeUser),stats={clients:users.filter(x=>x.role==='client').length,viewers:users.filter(x=>x.role==='viewer').length,pendingUsers:users.filter(x=>!x.approved).length,ads:d.ads.length,pendingAds:d.ads.filter(x=>x.status==='pending').length,payments:d.payments.reduce((n,x)=>n+Number(x.amount||0),0),withdrawals:d.withdrawals.reduce((n,x)=>n+Number(x.amount||0),0),viewerEarnings:users.filter(x=>x.role==='viewer').reduce((n,x)=>n+Number(x.balance||0),0)};return json(res,200,{admin:safeUser(d.admin),users,ads:d.ads,payments:d.payments,withdrawals:d.withdrawals,stats})}
  if(p==='/api/admin/action'&&req.method==='POST'){const b=await body(req),d=db();if(b.key!=='Admin@123')return json(res,401,{error:'Admin authentication required'});
    if(b.action==='approveUser'){const x=findUser(d,b.id);if(!x)return json(res,404,{error:'User not found'});x.approved=true;save(d);return json(res,200,{ok:true})}
    if(b.action==='rejectUser'){d.users=d.users.filter(x=>x.id!==b.id);save(d);return json(res,200,{ok:true})}
    if(b.action==='approveAd'){const a=d.ads.find(x=>x.id===b.id);if(!a)return json(res,404,{error:'Ad not found'});a.status='approved';a.approvedAt=new Date().toISOString();save(d);return json(res,200,{ok:true})}
    if(b.action==='rejectAd'){d.ads=d.ads.filter(x=>x.id!==b.id);save(d);return json(res,200,{ok:true})}
    if(b.action==='payment'){const x=findUser(d,b.userId);if(!x||x.role!=='client')return json(res,404,{error:'Client not found'});const pay={id:id('PAY'),userId:x.id,amount:Number(b.amount)||0,note:String(b.note||'').slice(0,200),date:new Date().toISOString()};d.payments.push(pay);save(d);return json(res,201,{payment:pay})}
    if(b.action==='withdrawStatus'){const w=d.withdrawals.find(x=>x.id===b.id);if(!w)return json(res,404,{error:'Withdrawal not found'});w.status=b.status||'processed';w.updatedAt=new Date().toISOString();save(d);return json(res,200,{ok:true})}
    return json(res,400,{error:'Unknown action'})
  }
  if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{error:'Method not allowed'});
  let rel=decodeURIComponent(p);if(rel==='/'||rel==='')rel='/index.html';const file=path.normalize(path.join(ROOT,rel));if(!file.startsWith(ROOT))return json(res,403,{error:'Forbidden'});fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream'});res.end(data)})
 }catch(e){console.error(e);json(res,500,{error:'Server error'})}
});server.listen(PORT,()=>console.log(`Add Dekho K server running on ${PORT}`));
